apiVersion: v1
kind: DeploymentConfig
metadata:
  name: inventory
spec:
  replicas: 1
  strategy:
    rollingParams:
      timeoutSeconds: 10800
    type: Rolling
  template:
    metadata:
      labels:
        app: inventory
        deploymentconfig: inventory
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JAVA_APP_DIR
          value: /deployments
        - name: JAVA_OPTIONS
          value: -Dswarm.project.stage=production

        ## Insert Volume Mounts here

        ## Insert health probes here

      ## Insert Volumes here

  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - inventory
      from:
        kind: ImageStreamTag
        name: inventory:latest
    type: ImageChange
